<?php

namespace Database\Seeders;

use App\Enums\SettingGroup;
use App\Enums\SettingType;
use App\Models\Setting;
use Illuminate\Database\Seeder;

class SettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->settings() as $setting) {
            Setting::firstOrCreate(
                ['key' => $setting['key']],
                $setting
            );
        }
    }

    /**
     * Get the default settings.
     *
     * @return array<int, array{key: string, value: ?string, group: SettingGroup, type: SettingType, description: string, options: ?array<string, string>, is_public: bool}>
     */
    private function settings(): array
    {
        return [
            // General settings
            [
                'key' => 'site_name',
                'value' => config('app.name', 'Laravel'),
                'group' => SettingGroup::General,
                'type' => SettingType::Text,
                'description' => 'The name of the platform displayed across the site.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'site_description',
                'value' => 'A powerful platform built with Laravel.',
                'group' => SettingGroup::General,
                'type' => SettingType::Textarea,
                'description' => 'A brief description of the platform.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'timezone',
                'value' => config('app.timezone', 'UTC'),
                'group' => SettingGroup::General,
                'type' => SettingType::Select,
                'description' => 'The default timezone for the platform.',
                'options' => [
                    'UTC' => 'UTC',
                    'America/New_York' => 'Eastern Time (US & Canada)',
                    'America/Chicago' => 'Central Time (US & Canada)',
                    'America/Denver' => 'Mountain Time (US & Canada)',
                    'America/Los_Angeles' => 'Pacific Time (US & Canada)',
                    'Europe/London' => 'London',
                    'Europe/Paris' => 'Paris',
                    'Europe/Berlin' => 'Berlin',
                    'Asia/Kolkata' => 'India (Kolkata)',
                    'Asia/Tokyo' => 'Tokyo',
                    'Asia/Shanghai' => 'Shanghai',
                    'Australia/Sydney' => 'Sydney',
                ],
                'is_public' => false,
            ],
            [
                'key' => 'date_format',
                'value' => 'Y-m-d',
                'group' => SettingGroup::General,
                'type' => SettingType::Select,
                'description' => 'The default date format used across the platform.',
                'options' => [
                    'Y-m-d' => '2026-01-15',
                    'd/m/Y' => '15/01/2026',
                    'm/d/Y' => '01/15/2026',
                    'd M Y' => '15 Jan 2026',
                    'M d, Y' => 'Jan 15, 2026',
                    'F j, Y' => 'January 15, 2026',
                ],
                'is_public' => false,
            ],
            [
                'key' => 'maintenance_mode',
                'value' => '0',
                'group' => SettingGroup::General,
                'type' => SettingType::Boolean,
                'description' => 'Enable maintenance mode to restrict access to the platform.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'allow_registration',
                'value' => '1',
                'group' => SettingGroup::General,
                'type' => SettingType::Boolean,
                'description' => 'Allow new users to register on the platform.',
                'options' => null,
                'is_public' => true,
            ],

            // Auth settings – General
            [
                'key' => 'auth_registration_enabled',
                'value' => '1',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Allow new users to register for an account.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_email_verification_required',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Require users to verify their email address.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_session_timeout_minutes',
                'value' => '120',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Number,
                'description' => 'Session timeout in minutes.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_min_password_length',
                'value' => '8',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Number,
                'description' => 'Minimum password length.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_recaptcha_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Protect login and registration forms with Google reCAPTCHA.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_recaptcha_site_key',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Google reCAPTCHA site key (required if reCAPTCHA is enabled).',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_recaptcha_secret_key',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Google reCAPTCHA secret key (required if reCAPTCHA is enabled).',
                'options' => null,
                'is_public' => false,
            ],

            // Auth settings – Social login
            [
                'key' => 'auth_github_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Enable sign in and sign up with GitHub.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_github_client_id',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'GitHub OAuth application Client ID.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_github_client_secret',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'GitHub OAuth application Client Secret.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_google_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Enable sign in and sign up with Google.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_google_client_id',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Google OAuth 2.0 Client ID.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_google_client_secret',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Google OAuth 2.0 Client Secret.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_github_redirect_uri',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Optional. Override callback URL for GitHub (e.g. http://localhost:8002/auth/github/callback). Leave blank to use the default from your app URL.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_google_redirect_uri',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Optional. Override callback URL for Google (e.g. http://localhost:8002/auth/google/callback). Leave blank to use the default from your app URL.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_facebook_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Allow users to sign in with their Facebook account.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_facebook_client_id',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Facebook App ID.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_facebook_client_secret',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Facebook App Secret.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_facebook_redirect_uri',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Optional. Override callback URL for Facebook. Leave blank to use the default from your app URL.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_twitter_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Enable sign in and sign up with Twitter / X.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_twitter_client_id',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Twitter (X) OAuth 2.0 Client ID.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_twitter_client_secret',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Twitter (X) OAuth 2.0 Client Secret.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_twitter_redirect_uri',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Optional. Override callback URL for Twitter. Leave blank to use the default from your app URL.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_linkedin_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Enable sign in and sign up with LinkedIn.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_linkedin_client_id',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'LinkedIn OAuth 2.0 Client ID.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_linkedin_client_secret',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'LinkedIn OAuth 2.0 Client Secret.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_linkedin_redirect_uri',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Optional. Override callback URL for LinkedIn. Leave blank to use the default from your app URL.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_gitlab_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Enable sign in and sign up with GitLab.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_gitlab_client_id',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'GitLab OAuth application Client ID.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_gitlab_client_secret',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'GitLab OAuth application Client Secret.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_gitlab_redirect_uri',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Optional. Override callback URL for GitLab. Leave blank to use the default from your app URL.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_bitbucket_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Enable sign in and sign up with Bitbucket.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_bitbucket_client_id',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Bitbucket OAuth consumer key (Client ID).',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_bitbucket_client_secret',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Bitbucket OAuth consumer secret (Client Secret).',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_bitbucket_redirect_uri',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Optional. Override callback URL for Bitbucket. Leave blank to use the default from your app URL.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_slack_enabled',
                'value' => '0',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Boolean,
                'description' => 'Enable sign in and sign up with Slack.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'auth_slack_client_id',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Slack OAuth application Client ID.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_slack_client_secret',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Slack OAuth application Client Secret.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'auth_slack_redirect_uri',
                'value' => '',
                'group' => SettingGroup::Auth,
                'type' => SettingType::Text,
                'description' => 'Optional. Override callback URL for Slack. Leave blank to use the default from your app URL.',
                'options' => null,
                'is_public' => false,
            ],

            // Mail settings
            [
                'key' => 'mail_from_name',
                'value' => config('app.name', 'Laravel'),
                'group' => SettingGroup::Mail,
                'type' => SettingType::Text,
                'description' => 'The name used as the sender for outgoing emails.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'mail_from_address',
                'value' => 'noreply@example.com',
                'group' => SettingGroup::Mail,
                'type' => SettingType::Text,
                'description' => 'The email address used as the sender for outgoing emails.',
                'options' => null,
                'is_public' => false,
            ],
            [
                'key' => 'mail_footer_text',
                'value' => 'Thank you for using our platform.',
                'group' => SettingGroup::Mail,
                'type' => SettingType::Textarea,
                'description' => 'Text displayed in the footer of all outgoing emails.',
                'options' => null,
                'is_public' => false,
            ],

            // SEO settings
            [
                'key' => 'meta_title',
                'value' => config('app.name', 'Laravel'),
                'group' => SettingGroup::Seo,
                'type' => SettingType::Text,
                'description' => 'Default meta title for the platform.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'meta_description',
                'value' => 'A powerful platform built with Laravel.',
                'group' => SettingGroup::Seo,
                'type' => SettingType::Textarea,
                'description' => 'Default meta description for search engines.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'meta_keywords',
                'value' => 'laravel, platform',
                'group' => SettingGroup::Seo,
                'type' => SettingType::Text,
                'description' => 'Default meta keywords for search engines (comma-separated).',
                'options' => null,
                'is_public' => true,
            ],

            // Social settings
            [
                'key' => 'social_facebook',
                'value' => '',
                'group' => SettingGroup::Social,
                'type' => SettingType::Text,
                'description' => 'Facebook page URL.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'social_twitter',
                'value' => '',
                'group' => SettingGroup::Social,
                'type' => SettingType::Text,
                'description' => 'Twitter/X profile URL.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'social_instagram',
                'value' => '',
                'group' => SettingGroup::Social,
                'type' => SettingType::Text,
                'description' => 'Instagram profile URL.',
                'options' => null,
                'is_public' => true,
            ],
            [
                'key' => 'social_linkedin',
                'value' => '',
                'group' => SettingGroup::Social,
                'type' => SettingType::Text,
                'description' => 'LinkedIn page URL.',
                'options' => null,
                'is_public' => true,
            ],

            // Billing settings
            [
                'key' => 'currency',
                'value' => 'USD',
                'group' => SettingGroup::Billing,
                'type' => SettingType::Select,
                'description' => 'Default currency for the platform.',
                'options' => [
                    'USD' => 'US Dollar (USD)',
                    'EUR' => 'Euro (EUR)',
                    'GBP' => 'British Pound (GBP)',
                    'INR' => 'Indian Rupee (INR)',
                    'JPY' => 'Japanese Yen (JPY)',
                    'AUD' => 'Australian Dollar (AUD)',
                    'CAD' => 'Canadian Dollar (CAD)',
                ],
                'is_public' => false,
            ],
            [
                'key' => 'tax_rate',
                'value' => '0',
                'group' => SettingGroup::Billing,
                'type' => SettingType::Number,
                'description' => 'Default tax rate percentage applied to transactions.',
                'options' => null,
                'is_public' => false,
            ],
        ];
    }
}
